# Generated by Django 4.2.30 on 2026-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('applied', 'Applied'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_docs', 'Needs Documents')], default='eligible', max_length=20)),
                ('application_ref', models.CharField(blank=True, max_length=100)),
                ('annual_amount', models.PositiveIntegerField()),
                ('missing_documents', models.JSONField(default=list)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entitlements',
                'ordering': ['-annual_amount'],
            },
        ),
    ]
