# Generated by Django 4.2.30 on 2026-06-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('schemes', '0001_initial'),
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='profiles.civicprofile'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('profile', 'scheme')},
        ),
    ]
