# Generated by Django 4.2.30 on 2026-06-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('caste_category', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS'), ('nt_dnt', 'NT/DNT')], max_length=20)),
                ('annual_income', models.PositiveIntegerField()),
                ('occupation', models.CharField(choices=[('farmer', 'Farmer'), ('labourer', 'Labourer'), ('skilled_trade', 'Skilled Trade'), ('small_business', 'Small Business'), ('salaried', 'Salaried'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30)),
                ('land_holding', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_size', models.PositiveIntegerField()),
                ('bpl_card', models.BooleanField(default=False)),
                ('aadhaar_linked', models.BooleanField(default=False)),
                ('pan_linked', models.BooleanField(default=False)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'civic_profiles',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='profiles.civicprofile')),
            ],
            options={
                'db_table': 'family_members',
            },
        ),
    ]
