# Generated by Django 4.2.30 on 2026-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnclaimedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('insurance', 'Insurance'), ('dividend', 'Dividend'), ('pension', 'Pension')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('RBI', 'RBI'), ('IRDAI', 'IRDAI'), ('SEBI', 'SEBI')], max_length=10)),
                ('reference', models.CharField(max_length=200)),
                ('claim_instructions', models.TextField(blank=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unclaimed_assets',
                'ordering': ['-amount'],
            },
        ),
    ]
