# Generated by Django 4.2.30 on 2026-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('health', 'Health'), ('education', 'Education'), ('housing', 'Housing'), ('pension', 'Pension'), ('welfare', 'Welfare')], max_length=20)),
                ('department', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('central', 'Central'), ('state', 'State'), ('local', 'Local')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('annual_benefit', models.PositiveIntegerField()),
                ('eligibility_summary', models.TextField()),
                ('eligibility_rules', models.JSONField()),
                ('documents_required', models.JSONField()),
                ('portal_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('launched_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schemes',
                'ordering': ['-annual_benefit'],
            },
        ),
    ]
